name: Sync Camel Spring Boot Master Branch

on:
  schedule:
    # Run every day at midnight
    - cron:  '5 * * * *'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          repository: apache/camel
          ref: master
          path: camel
      - name: Set Up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Project
        run: /home/runner/work/test-camel-build-actions/camel/mvnw clean install -DskipTests
